[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  KINDE_CLIENT_ID = "f2f292d4a983424ab838c4ecddfe8038"
  KINDE_CLIENT_SECRET = "tyWiNFFJMG4fHag9T0PSPW0S3aoRegKEeq1CMOfHe8HA9Et2S"
  KINDE_ISSUER_URL = "https://modelflow.kinde.com"
  KINDE_SITE_URL = "http://localhost:3000"
  KINDE_POST_LOGOUT_REDIRECT_URL = "http://localhost:3000"
  KINDE_POST_LOGIN_REDIRECT_URL = "http://localhost:3000/profile"